import { SPRINT_TOTAL_SECONDS } from "../constants";
import { getConfig } from "../config";

export const createInitialState = () => ({
  screen: "splash",
  provider: "foundry",
  apiKey: "",
  foundryKey: "",
  foundryProjectEndpoint: getConfig(
    ["AZURE_AI_PROJECT_ENDPOINT", "AZURE_EXISTING_AIPROJECT_ENDPOINT", "FOUNDRY_PROJECT_ENDPOINT", "foundryProjectEndpoint"],
    "https://res-jsaibuildathon.services.ai.azure.com/api/projects/jsaibuildathon"
  ),
  foundryOpenAiEndpoint: getConfig(
    ["AZURE_OPENAI_ENDPOINT", "FOUNDRY_OPENAI_ENDPOINT", "foundryOpenAiEndpoint"],
    "https://res-jsaibuildathon.openai.azure.com/openai/v1"
  ),
  foundryDeployment: getConfig(["AZURE_OPENAI_DEPLOYMENT", "FOUNDRY_DEPLOYMENT", "foundryDeployment"], "gpt-4.1-mini"),
  foundryAgentEnabled: getConfig(["FOUNDRY_AGENT_ENABLED", "foundryAgentEnabled"], "false").toLowerCase() === "true",
  foundryAgentName: getConfig(["FOUNDRY_AGENT_NAME", "foundryAgentName"], "StudioMillionaireAgent"),
  foundryAgentVersion: getConfig(["FOUNDRY_AGENT_VERSION", "foundryAgentVersion"], ""),
  foundryAgentAutoApprove: getConfig(["FOUNDRY_AGENT_AUTO_APPROVE", "foundryAgentAutoApprove"], "true").toLowerCase() !== "false",
  customShowEnabled: getConfig(["CUSTOM_SHOW_ENABLED", "customShowEnabled"], "false").toLowerCase() === "true",
  customShowTitle: getConfig(["CUSTOM_SHOW_TITLE", "customShowTitle"], "Studio Millionaire Custom Show"),
  customShowTopic: getConfig(["CUSTOM_SHOW_TOPIC", "customShowTopic"], ""),
  customShowSource: getConfig(["CUSTOM_SHOW_SOURCE", "customShowSource"], ""),
  customShowPlan: null,
  customShowPlanSignature: "",
  customShowPlanning: false,
  model: "claude-sonnet-4-20250514",
  soundEnabled: true,
  gameMode: "career",
  currentStageKey: "recruit",
  unlockedStages: ["recruit"],
  completedStages: [],
  bestStageProgress: {},
  sprintBestScore: 0,
  checkpoint: null,
  qNum: 0,
  currentQ: null,
  currentTopic: null,
  currentGrounding: null,
  selectedAnswer: null,
  revealedCorrect: false,
  usedLifelines: { fifty: 1, audience: 1, phone: 1 },
  settingsOpen: false,
  settingsTab: "model",
  status: "",
  feedbackType: "",
  feedbackMsg: "",
  eliminated: [],
  hintText: "",
  loading: false,
  answering: false,
  errorMsg: "",
  sprint: {
    timeLeft: SPRINT_TOTAL_SECONDS,
    score: 0,
    streak: 0,
    newBest: false,
    paused: false,
    pausePending: false,
    timerFreezeQuestions: 0,
    finishReason: "",
    claimedPrizeTiers: [],
  },
  bonusPoints: 0,
  rewardWallet: { loot: 0, gems: 0, tokens: 0 },
  shopOpen: false,
  rewardGuideOpen: false,
  redeemedItems: [],
});
